name: Deploy Trading App to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
  AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build
      env:
        NEXT_PUBLIC_BINANCE_API_KEY: ${{ secrets.NEXT_PUBLIC_BINANCE_API_KEY }}
        BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
        NEXT_PUBLIC_AZURE_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_AZURE_API_BASE_URL }}
        NEXT_PUBLIC_AZURE_API_KEY: ${{ secrets.NEXT_PUBLIC_AZURE_API_KEY }}
        NEXT_PUBLIC_USE_MOCK_DATA: ${{ secrets.NEXT_PUBLIC_USE_MOCK_DATA }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: |
          .next/
          package.json
          package-lock.json
          public/
        retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-files

    - name: Setup Azure Developer CLI
      uses: Azure/setup-azd@v1.0.0

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"

    - name: Log in with Azure (JSON Credentials)
      run: |
        echo '${{ secrets.AZURE_CREDENTIALS }}' > azure-credentials.json
        azd auth login --client-credentials azure-credentials.json
        rm azure-credentials.json

    - name: Azure Dev Provision
      run: azd provision --no-prompt
      env:
        AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
        AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
        NEXT_PUBLIC_BINANCE_API_KEY: ${{ secrets.NEXT_PUBLIC_BINANCE_API_KEY }}
        BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
        NEXT_PUBLIC_AZURE_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_AZURE_API_BASE_URL }}
        NEXT_PUBLIC_AZURE_API_KEY: ${{ secrets.NEXT_PUBLIC_AZURE_API_KEY }}
        NEXT_PUBLIC_USE_MOCK_DATA: ${{ secrets.NEXT_PUBLIC_USE_MOCK_DATA }}

    - name: Azure Dev Deploy
      run: azd deploy --no-prompt
      env:
        AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
        AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
        NEXT_PUBLIC_BINANCE_API_KEY: ${{ secrets.NEXT_PUBLIC_BINANCE_API_KEY }}
        BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
        NEXT_PUBLIC_AZURE_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_AZURE_API_BASE_URL }}
        NEXT_PUBLIC_AZURE_API_KEY: ${{ secrets.NEXT_PUBLIC_AZURE_API_KEY }}
        NEXT_PUBLIC_USE_MOCK_DATA: ${{ secrets.NEXT_PUBLIC_USE_MOCK_DATA }}
